import Head from 'next/head';
import ghost from '../lib/services/ghost';

export default function Home({ posts }: { posts: any }) {
  return (
    <>
      <Head>
        <title>GoodXP By Abdullah Faruk</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {posts.map((post: any) => (
          <p>{post.title}</p>
        ))}
      </div>
    </>
  );
}

export async function getStaticProps() {
  const posts = await ghost.getPosts();

  if (!posts) {
    return {
      notFound: true,
    };
  }

  return {
    props: { posts },
  };
}
